services:
  vue:
    build:
      context: ./frontend
      dockerfile: ../docker/vue/Dockerfile
    container_name: crm_vue
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - crm-network

  php:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: crm_php
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - crm-network

  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - crm-network

  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crm_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
    volumes:
      - mysql-data:/var/liv/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - crm-network

volumes:
  mysql-data:

networks:
  crm-network:
    driver: bridge
